name: omni_bar
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.2

environment:
  sdk: ^3.10.7

dependencies:
  desktop_multi_window: ^0.3.0
  flutter:
    sdk: flutter
  hotkey_manager: ^0.2.3
  launch_at_startup: ^0.5.1
  macos_ui: ^2.2.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  system_tray: ^2.0.3
  uuid: ^3.0.7
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tray_icon.png
